version: "3.7"
services:
  mariadb:
    image: "mariadb:latest"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: jeedom
      MYSQL_USER: jeedom
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  jeedom:
    build: "."
    image: "jeedom:V4-release"
    depends_on:
      - mariadb
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
